import type { RouteObject } from "react-router";

// This file will be auto-generated by React Router v7
// For now, we'll use the file-based routing from the app/routes directory
const routes: RouteObject[] = [];

export default routes;
