-- AlterTable
ALTER TABLE "Challenge" ADD COLUMN     "commentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "likeCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Note" ADD COLUMN     "replyCount" INTEGER NOT NULL DEFAULT 0;
